### ISSUE TITLE
Seems like steps for installing rapidmx and pngview are not working anymore

### ISSUE THREAD

**Issue by tusabez** [d-rez/gbz_overlay#3]
I'm getting this error message when trying to run the initial steps in the guide: /usr/bin/ld: cannot find -lraspidmx  /usr/bin/ld: cannot find -lraspidmxPng. Any suggestions to proceed would be appreciated.

**Comment by d-rez** [comment]
~~Initial steps for raspidmx are generic. If you believe there's an issue with the source code of raspidmx, I'd suggest checking the Issues section of the repository itself to check if it's failing for others as well:~~
 ~~https://github.com/AndrewFromMelbourne/raspidmx~~

~~I will however try building it tomorrow and see if I get any errors~~ 

There is no issue with raspidmx, just looks like it's not possible to build it without building the whole package anymore. It builds OK

**Comment by d-rez** [comment]
The following should work just fine:

```
mkdir ~/src && cd ~/src 
git clone --depth 1 https://github.com/AndrewFromMelbourne/raspidmx.git 
cd raspidmx/ 
make -j4
sudo cp pngview/pngview /usr/local/bin/
``` 

Let me know if it works for you and I'll update the readme

**Comment by tusabez** [comment]
That did the trick! Thanks!
